return {
  "rose-pine/neovim",
  enabled = true,
  lazy = false,
  priority = 1000,
  name = "rose-pine",
  opts = {
    dim_inactive_windows = true,
    highlight_groups = {
      ExtraWhitespace = { fg = "love", bg = "love", blend = 20 },
      ["@markup.link.label"] = {},
      LuasnipInsertNodePassive = { bg = "gold", blend = 20 },
      LuasnipChoiceNodePassive = { bg = "gold", blend = 20 },
      BlinkCmpDocBorder = { fg = "highlight_high", bg = "highlight_low" },
      PmenuSel = { fg = "none", bg = "overlay" },
      BufferLineTabSelected = { fg = "text", bg = "base" },
      CmpKitMarkdownAnnotateUnderlined = { fg = "foam", sp = "foam", underline = true },
      CmpKitMarkdownAnnotateBold = { fg = "foam", bold = true },
      CmpKitMarkdownAnnotateEm = { fg = "foam", sp = "foam", bold = true, underline = true },
      CmpKitMarkdownAnnotateStrong = { bg = "iris", blend = 15, sp = "iris", bold = true },
      CmpKitMarkdownAnnotateCodeBlock = { bg = "overlay", blend = 30 },
      CmpKitMarkdownAnnotateHeading1 = { fg = "foam", blend = 30 },
      CmpKitMarkdownAnnotateHeading2 = { fg = "foam", blend = 30 },
      CmpKitMarkdownAnnotateHeading3 = { fg = "foam", blend = 30 },
      CmpKitMarkdownAnnotateHeading4 = { fg = "foam", blend = 30 },
      CmpKitMarkdownAnnotateHeading5 = { fg = "foam", blend = 30 },
      CmpKitMarkdownAnnotateHeading6 = { fg = "foam", blend = 30 },
      CmpKitDeprecated = { fg = "subtle", sp = "subtle", strikethrough = true },
      CmpKitCompletionItemLabel = { fg = "subtle" },
      CmpKitCompletionItemDescription = { fg = "muted" },
      CmpKitCompletionItemMatch = { fg = "text", bold = true },
      CmpKitCompletionItemExtra = { fg = "muted" },
      CmpKitCompletionItemKind_Interface = { fg = "foam" },
      CmpKitCompletionItemKind_TypeParameter = { fg = "foam" },
      CmpKitCompletionItemKind_Color = { fg = "foam" },
      CmpKitCompletionItemKind_Field = { fg = "foam" },
      CmpKitCompletionItemKind_Value = { fg = "foam" },
      CmpKitCompletionItemKind_Snippet = { fg = "gold" },
      CmpKitCompletionItemKind_Enum = { fg = "foam" },
      CmpKitCompletionItemKind_Event = { fg = "foam" },
      CmpKitCompletionItemKind_Constructor = { fg = "foam" },
      CmpKitCompletionItemKind_EnumMember = { fg = "foam" },
      CmpKitCompletionItemKind_Folder = { fg = "foam" },
      CmpKitCompletionItemKind_Module = { fg = "foam" },
      CmpKitCompletionItemKind_File = { fg = "foam" },
      CmpKitCompletionItemKind_Property = { fg = "foam" },
      CmpKitCompletionItemKind_Method = { fg = "iris" },
      CmpKitCompletionItemKind_Constant = { fg = "foam" },
      CmpKitCompletionItemKind_Variable = { fg = "text" },
      CmpKitCompletionItemKind_Reference = { fg = "foam" },
      CmpKitCompletionItemKind_Unit = { fg = "foam" },
      CmpKitCompletionItemKind_Struct = { fg = "foam" },
      CmpKitCompletionItemKind_Function = { fg = "rose" },
      CmpKitCompletionItemKind_Class = { fg = "foam" },
      CmpKitCompletionItemKind_Keyword = { fg = "foam" },
      CmpKitCompletionItemKind_Text = { fg = "foam" },
      CmpKitCompletionItemKind_Operator = { fg = "foam" },
    },
  },
}
