require("focus").setup({
  autoresize = true,
  signcolumn = true,
  cursorline = false,
})

vim.keymap.set("n", "<leader>h", function()
  vim.cmd("FocusSplitLeft")
  vim.cmd("InclineUpdate")
end, { silent = true, desc = "FocusSplitLeft" })
vim.keymap.set("n", "<leader>j", function()
  vim.cmd("FocusSplitDown")
  vim.cmd("InclineUpdate")
end, { silent = true, desc = "FocusSplitDown" })
vim.keymap.set("n", "<leader>k", function()
  vim.cmd("FocusSplitUp")
  vim.cmd("InclineUpdate")
end, { silent = true, desc = "FocusSplitUp" })
vim.keymap.set("n", "<leader>l", function()
  vim.cmd("FocusSplitRight")
  vim.cmd("InclineUpdate")
end, { silent = true, desc = "FocusSplitRight" })
vim.keymap.set("n", "<leader>=", function()
  vim.cmd("FocusEqualise")
  vim.cmd("InclineUpdate")
end, { silent = true, desc = "FocusEqualise" })
vim.keymap.set("n", "<leader>z", function()
  vim.cmd("FocusMaxOrEqual")
  vim.cmd("InclineUpdate")
end, { silent = true, desc = "FocusMaximise" })
vim.keymap.set("n", "<leader><leader>f", function()
  vim.cmd("FocusToggle")
  vim.cmd("InclineUpdate")
end, { silent = true, desc = "FocusToggle" })
