require('lsp.bashls')
-- require('lsp.tsserver')
require('lsp.angularls')
require('lsp.html')
require('lsp.cssls')
require('lsp.vimls')
require('lsp.yamlls')
require('lsp.jsonls')
require('lsp.lua_ls')
require('lsp.clangd')
require('lsp.taplo') -- TOML
require('lsp.tailwindcss') -- TOML
require('lsp.pyright')
require('lsp.marksman')
-- require('lsp.emmet-language-server')
-- require('lsp.volar')
-- require('lsp.sqlls')

-- require('lsp.diagnosticls')
-- require('lsp.sqls')
-- require('lsp.ccls')
-- require('lsp.pyright')
-- require('lsp.graphql')
-- require('lsp.efm')
require('lsp.eslint')
-- require('lsp.lsemmet')
