return {
  "WhoIsSethDaniel/mason-tool-installer.nvim",
  opts = {
    ensure_installed = {
      "bash-language-server",
      "typescript-language-server",
      "angular-language-server",
      "html-lsp",
      "css-lsp",
      "vim-language-server",
      "yaml-language-server",
      "json-lsp",
      "lua-language-server",
      "clangd",
      "taplo",
      "tailwindcss-language-server",
      "pyright",
      "diagnostic-languageserver",
      "efm",
      "vue-language-server",
      "marksman",
      "emmet-language-server",
      "astro-language-server",
      "rust-analyzer",
      -- formatters
      "black",
      "sql-formatter",
      "prettier",
      "prettierd",
      "stylua",
      "autopep8",
      "eslint-lsp",
      "eslint_d",
    },
  },
}
