return {
  "nvim-tree/nvim-web-devicons",
  opts = {
    override = {
      ["cs"] = {
        icon = "󰌛",
        color = "#596706",
        cterm_color = "58",
        name = "Cs",
      },
      ["csv"] = {
        icon = "󰈙",
        color = "#89e051",
        cterm_color = "113",
        name = "Csv",
      },
      ["doc"] = {
        icon = "󰈬",
        color = "#185abd",
        cterm_color = "26",
        name = "Doc",
      },
      ["docx"] = {
        icon = "󰈬",
        color = "#185abd",
        cterm_color = "26",
        name = "Docx",
      },
      ["material"] = {
        icon = "󰔉",
        color = "#B83998",
        cterm_color = "163",
        name = "Material",
      },
      ["mint"] = {
        icon = "󰌪",
        color = "#87c095",
        cterm_color = "108",
        name = "Mint",
      },
      ["opus"] = {
        icon = "󰈣",
        color = "#F88A02",
        cterm_color = "208",
        name = "OPUS",
      },
      ["ppt"] = {
        icon = "󰈧",
        color = "#cb4a32",
        cterm_color = "214",
        name = "Ppt",
      },
      ["r"] = {
        icon = "󰟔",
        color = "#358a5b",
        cterm_color = "29",
        name = "R",
      },
      ["rproj"] = {
        icon = "󰗆",
        color = "#358a5b",
        cterm_color = "29",
        name = "Rproj",
      },
      ["scm"] = {
        icon = "󰘧",
        color = "#000000",
        cterm_color = "16",
        name = "Scheme",
      },
      ["sv"] = {
        icon = "󰍛",
        color = "#019833",
        cterm_color = "28",
        name = "SystemVerilog",
      },
      ["svh"] = {
        icon = "󰍛",
        color = "#019833",
        cterm_color = "28",
        name = "SystemVerilog",
      },
      ["svg"] = {
        icon = "󰜡",
        color = "#FFB13B",
        cterm_color = "214",
        name = "Svg",
      },
      ["tbc"] = {
        icon = "󰛓",
        color = "#1e5cb3",
        cterm_color = "25",
        name = "Tcl",
      },
      ["tex"] = {
        icon = "󰙩",
        color = "#3D6117",
        cterm_color = "22",
        name = "Tex",
      },
      ["tscn"] = {
        icon = "󰎁",
        color = "#a074c4",
        cterm_color = "140",
        name = "TextScene",
      },
      ["txt"] = {
        icon = "󰈙",
        color = "#89e051",
        cterm_color = "113",
        name = "Txt",
      },
      ["v"] = {
        icon = "󰍛",
        color = "#019833",
        cterm_color = "28",
        name = "Verilog",
      },
      ["vh"] = {
        icon = "󰍛",
        color = "#019833",
        cterm_color = "28",
        name = "Verilog",
      },
      ["vhd"] = {
        icon = "󰍛",
        color = "#019833",
        cterm_color = "28",
        name = "VHDL",
      },
      ["vhdl"] = {
        icon = "󰍛",
        color = "#019833",
        cterm_color = "28",
        name = "VHDL",
      },
      ["webpack"] = {
        icon = "󰜫",
        color = "#519aba",
        cterm_color = "74",
        name = "Webpack",
      },
      ["xls"] = {
        icon = "󰈛",
        color = "#207245",
        cterm_color = "29",
        name = "Xls",
      },
      ["xlsx"] = {
        icon = "󰈛",
        color = "#207245",
        cterm_color = "29",
        name = "Xlsx",
      },
      ["xml"] = {
        icon = "󰗀",
        color = "#e37933",
        cterm_color = "166",
        name = "Xml",
      },
      ["sol"] = {
        icon = "󰞻",
        color = "#519aba",
        cterm_color = "74",
        name = "Solidity",
      },
      ["prisma"] = {
        icon = "󰔶",
        color = "#ffffff",
        cterm_color = "231",
        name = "Prisma",
      },
    },
  },
}
